### PR TITLE
fix hard refresh with meta tags. disable caching using index.html

### PR DESCRIPTION
**Pull request by dagogodboss**
This PR try to Prevent the HTTP CACHE Content

to avoid the user from hard-refreshing

[Loom Video](https://www.loom.com/share/2754b6ed33a64105a8c023e4bdf760dd)

### CODE REVIEW

**Comment by kayroy247** [comment]
The reloading issue still persisted when I tested deployed PR link. Kindly check.

- Loom video of my test: https://www.loom.com/share/abb94f3b2707443d85a332899bd2d4eb
- Deployed PR link: https://deploy-preview-27--smartswap.netlify.app/swap

**Comment by codefingas** [comment]
> The reloading issue still persisted when I tested deployed PR link. Kindly check.
> 
> * Loom video of my test: https://www.loom.com/share/abb94f3b2707443d85a332899bd2d4eb
> * Deployed PR link: https://deploy-preview-27--smartswap.netlify.app/swap

couldn't reproduce error in Loom video

**Comment by dagogodboss** [comment]
> 
> 
> The reloading issue still persisted when I tested deployed PR link. Kindly check.
> 
>     * Loom video of my test: https://www.loom.com/share/abb94f3b2707443d85a332899bd2d4eb
> 
>     * Deployed PR link: https://deploy-preview-27--smartswap.netlify.app/swap

So this happen when you are not connected to the right network, I got this error on Ropsten Network

**Comment by kayroy247** [comment]
> > The reloading issue still persisted when I tested deployed PR link. Kindly check.
> > ```
> > * Loom video of my test: https://www.loom.com/share/abb94f3b2707443d85a332899bd2d4eb
> > 
> > * Deployed PR link: https://deploy-preview-27--smartswap.netlify.app/swap
> > ```
> 
> So this happen when you are not connected to the right network, I got this error on Ropsten Network

I got the error when I switched to bsc mainnet. I am testing between BSC mainnet and bsc testnet. I did not use other network to test.

**Pull request merged**
