### PR TITLE
feat: display price history on the chart graph

### PR DESCRIPTION
**Pull request by Goodiec**
What does the PR do?
- Display real-time RGB to BNB price on the chart graph
- Display 24hr volume

What are the tasks completed?
- Display real-time RGB to BNB price on the chart graph
- Display 24hr volume

Loom Video: https://www.loom.com/share/aa0140ec59044077a43031228a02d76b

### CODE REVIEW

**Review by fakoredeDamilola — COMMENTED** [review]
Looks good

**Comment by Goodiec** [comment]
@kayroy247, kindly review this PR.

**Comment by kayroy247** [comment]
> @kayroy247, kindly review this PR.
I think other data are okay but the graph indicates that 1 RGP is 0.00058 which is different from the current price data. Here is a screenshot.
rgpdata

**Comment by Goodiec** [comment]
> > @kayroy247, kindly review this PR.
> > I think other data are okay but the graph indicates that 1 RGP is 0.00058 which is different from the current price data. Here is a screenshot.
> > rgpdata

Fixed

**Pull request merged**
