### PR TITLE
Feat extended token list

### PR DESCRIPTION
**Pull request by dagogodboss**
# Extended Token List

- This PR allows users to add Custom token by Address
- Allow users to import Custom Token List using URI.
- This PR Create a Default Token List using BSC scan Site.
-  Allows user turn off Token List
-  Sync import token with Default token List, using both the search field and import menu. 

[Loom Video](https://www.loom.com/share/fa27c029e48e4d3d920d9ad8de19f8f3)

### CODE REVIEW

**Comment by OnahProsperity** [comment]
please kindly note, cant access the loom video as it keeps loading forever.

**Comment by kayroy247** [comment]
I tested and it seems the PR may introduce a bug. The yield farming data is not loaded on this deployed PR link due to some errors that can be seen in the browser console. kindly check. https://deploy-preview-64--smartswap.netlify.app/farming

**Comment by kayroy247** [comment]
The content of this modal also flickers as if it's rerendering multiple times. https://www.loom.com/share/9eeda680154849c093c3f00c28a72de8

**Comment by kayroy247** [comment]
clicking the manage token button makes the page go blank. Kindly check. Here is a loom video of my test: https://www.loom.com/share/9be8312b44324a71841a5e3529a93e94

**Comment by kayroy247** [comment]
The BUSD and BNB logos are larger than expected. 
largeicon

**Comment by dagogodboss** [comment]
> 1. The BUSD and BNB logos are larger than expected.
>    largeicon
> 2. From the task description, RGP is supposed to be on the top of the list: https://linear.app/rigelprotocol-dev/issue/RSMA-24/robust-token-lists-on-the-dapp

Refresh your browser that is not the case. You have cache files.

**Pull request merged**
